name = "memorial-backend"
main = "src/index.js"
compatibility_date = "2024-03-20"
workers_dev = true

# Automatically serve static files from the "public" folder
[assets]
directory = "public"

[[d1_databases]]
binding = "memorial_db"
database_name = "memorial-db"
database_id = "fc3cf1d0-6180-4579-a8c7-f4b300f9636e"

[[r2_buckets]]
bucket_name = "memorial-photos"
binding = "memorial_photos"
